spring:
  datasource:
    url: jdbc:mysql://localhost:3306/userservicedb?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true

